/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.filipeborges.poc.spring.log_tracing.log;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
